// Generated by gencpp from file tag_detector/ServiceMsgResponse.msg
// DO NOT EDIT!


#ifndef TAG_DETECTOR_MESSAGE_SERVICEMSGRESPONSE_H
#define TAG_DETECTOR_MESSAGE_SERVICEMSGRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tag_detector
{
template <class ContainerAllocator>
struct ServiceMsgResponse_
{
  typedef ServiceMsgResponse_<ContainerAllocator> Type;

  ServiceMsgResponse_()
    : isSetOK(false)  {
    }
  ServiceMsgResponse_(const ContainerAllocator& _alloc)
    : isSetOK(false)  {
  (void)_alloc;
    }



   typedef uint8_t _isSetOK_type;
  _isSetOK_type isSetOK;





  typedef boost::shared_ptr< ::tag_detector::ServiceMsgResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tag_detector::ServiceMsgResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ServiceMsgResponse_

typedef ::tag_detector::ServiceMsgResponse_<std::allocator<void> > ServiceMsgResponse;

typedef boost::shared_ptr< ::tag_detector::ServiceMsgResponse > ServiceMsgResponsePtr;
typedef boost::shared_ptr< ::tag_detector::ServiceMsgResponse const> ServiceMsgResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tag_detector::ServiceMsgResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tag_detector::ServiceMsgResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tag_detector

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tag_detector::ServiceMsgResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tag_detector::ServiceMsgResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tag_detector::ServiceMsgResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tag_detector::ServiceMsgResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tag_detector::ServiceMsgResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tag_detector::ServiceMsgResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tag_detector::ServiceMsgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c864c7a1d4f7d9d28b33390ae7e7d71d";
  }

  static const char* value(const ::tag_detector::ServiceMsgResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc864c7a1d4f7d9d2ULL;
  static const uint64_t static_value2 = 0x8b33390ae7e7d71dULL;
};

template<class ContainerAllocator>
struct DataType< ::tag_detector::ServiceMsgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tag_detector/ServiceMsgResponse";
  }

  static const char* value(const ::tag_detector::ServiceMsgResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tag_detector::ServiceMsgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool isSetOK\n\
\n\
";
  }

  static const char* value(const ::tag_detector::ServiceMsgResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tag_detector::ServiceMsgResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.isSetOK);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServiceMsgResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tag_detector::ServiceMsgResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tag_detector::ServiceMsgResponse_<ContainerAllocator>& v)
  {
    s << indent << "isSetOK: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isSetOK);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TAG_DETECTOR_MESSAGE_SERVICEMSGRESPONSE_H
