// Generated by gencpp from file tag_detector/ServiceMsg.msg
// DO NOT EDIT!


#ifndef TAG_DETECTOR_MESSAGE_SERVICEMSG_H
#define TAG_DETECTOR_MESSAGE_SERVICEMSG_H

#include <ros/service_traits.h>


#include <tag_detector/ServiceMsgRequest.h>
#include <tag_detector/ServiceMsgResponse.h>


namespace tag_detector
{

struct ServiceMsg
{

typedef ServiceMsgRequest Request;
typedef ServiceMsgResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ServiceMsg
} // namespace tag_detector


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tag_detector::ServiceMsg > {
  static const char* value()
  {
    return "b8e47ef395f4ff61960de951a76c82dd";
  }

  static const char* value(const ::tag_detector::ServiceMsg&) { return value(); }
};

template<>
struct DataType< ::tag_detector::ServiceMsg > {
  static const char* value()
  {
    return "tag_detector/ServiceMsg";
  }

  static const char* value(const ::tag_detector::ServiceMsg&) { return value(); }
};


// service_traits::MD5Sum< ::tag_detector::ServiceMsgRequest> should match 
// service_traits::MD5Sum< ::tag_detector::ServiceMsg > 
template<>
struct MD5Sum< ::tag_detector::ServiceMsgRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tag_detector::ServiceMsg >::value();
  }
  static const char* value(const ::tag_detector::ServiceMsgRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tag_detector::ServiceMsgRequest> should match 
// service_traits::DataType< ::tag_detector::ServiceMsg > 
template<>
struct DataType< ::tag_detector::ServiceMsgRequest>
{
  static const char* value()
  {
    return DataType< ::tag_detector::ServiceMsg >::value();
  }
  static const char* value(const ::tag_detector::ServiceMsgRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tag_detector::ServiceMsgResponse> should match 
// service_traits::MD5Sum< ::tag_detector::ServiceMsg > 
template<>
struct MD5Sum< ::tag_detector::ServiceMsgResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tag_detector::ServiceMsg >::value();
  }
  static const char* value(const ::tag_detector::ServiceMsgResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tag_detector::ServiceMsgResponse> should match 
// service_traits::DataType< ::tag_detector::ServiceMsg > 
template<>
struct DataType< ::tag_detector::ServiceMsgResponse>
{
  static const char* value()
  {
    return DataType< ::tag_detector::ServiceMsg >::value();
  }
  static const char* value(const ::tag_detector::ServiceMsgResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TAG_DETECTOR_MESSAGE_SERVICEMSG_H
